fix constant folding issue: Resize from torch UpsamplingBilinear2d
kneron/ONNX_Convertor pull request #44
Opened 2021-02-02 11:14 UTC by ericwu155214

Hi,

I fix some constant folding issue in case of onnx from pytorch.
It happen when pytorch user use nn.UpsamplingBilinear2d

please check it.
Thanks!

2021-02-02 11:34 UTC, MrWhoami requested changes

2021-02-02 11:34 UTC, MrWhoami commented on optimizer_scripts/tools/other.py
> +            print(duplicated_node)
Please remove this debug print.

2021-02-02 14:11 UTC, ericwu155214 commented on optimizer_scripts/tools/other.py
> +            print(duplicated_node)
Oh, let me remove it

2021-02-02 14:16 UTC, ericwu155214 commented on optimizer_scripts/tools/other.py
> +            print(duplicated_node)
done

2021-02-03 09:54 UTC, MrWhoami approved these changes

2021-02-03 09:54 UTC, merged